### ISSUE TITLE
Unity WebGL server responded with a status of 404

### ISSUE THREAD

**Issue by iiLam1688** [itchio/itch.io#1149]
have warning show at jsStackTrace(https://iilam1688.github.io/Speed-and-knowledge/Build/WebGL2.framework.js:739:12)
at StackTrace(https://iilam1688.github.io/Speed-and-knowledge/Build/WebGL2.framework.js:753:11)
at abort(https://iilam1688.github.io/Speed-and-knowledge/Build/WebGL2.framework.js:19:44)
at (https://iilam1688.github.io/Speed-and-knowledge/Build/WebGL2.framework.js:1179:5)
how to solve this problem

**Comment by leafo** [comment]
HTML games run arbitrary code that you provide, debugging your game's code is generally outside the scope of what we do. I recommend using your browser console to see if you can discover why the error is thrown.

Here are some common pitfalls with HTML5 games that might help you, pay close attention to the section about absolute paths and case sensitivity: https://itch.io/docs/creators/html5#common-pitfalls
